---
- hosts: "{{ HOSTS }}"
  become: yes

  tasks:
  - name: Send notification message via Slack
    community.general.slack:
      token: {{ slack_token }}
      msg: {{ MESSAGE }}
      channel: #ansible-bot
    delegate_to: localhost
