---
- hosts: "{{ HOSTS }}"
  become: yes
  vars:
    #check_only: yes
    check_only: "{{ CHECK }}"

  tasks:
  - name: check operating system
    assert:
      that: "ansible_os_family == 'RedHat'"

  - name: check for updates
    yum:
      name: '*'
      state: latest
      exclude: kernel*
    check_mode: "{{ check_only }}"
    register: updates

  - name: output updates dictionary
    debug:
      msg: "{{ updates }}"
