---

- name: Create ServiceNOW Ticket for a Change
  hosts: localhost
  connection: local
  gather_facts: true
  run_once: true
  vars_files:
    - group_vars/credentials.yml

  tasks:
  - include_role:
      name: servicenow_changerequest
